#!/bin/bash
# labs/21B-proc-sysctl.sh
# Lab: The /proc Filesystem and Persistent Kernel Tunables with sysctl
# Difficulty: Intermediate
# RHCSA Objective: Adjust kernel parameters; make kernel parameter changes persistent

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../lab-runner.sh"

LAB_NAME="The /proc Filesystem and Persistent Kernel Tunables"
LAB_DIFFICULTY="Intermediate"
LAB_TIME_ESTIMATE="15-20 minutes"

#############################################################################
# SETUP
#############################################################################
setup_lab() {
    echo "Preparing lab environment..."

    # Remove any leftover lab sysctl config from a previous attempt
    rm -f /etc/sysctl.d/lab21b.conf 2>/dev/null || true

    # Reset the tunable we'll be working with to its default (0 = disabled)
    # net.ipv4.ip_forward controls IP packet forwarding (routing behavior)
    echo 0 > /proc/sys/net/ipv4/ip_forward 2>/dev/null || true

    echo "  ✓ Cleared any previous lab sysctl config"
    echo "  ✓ net.ipv4.ip_forward reset to 0"
    echo "  ✓ System ready for fresh lab start"
}

#############################################################################
# PREREQUISITES
#############################################################################
prerequisites() {
    cat << 'EOF'
Knowledge Requirements:
  • That /proc is a pseudo-filesystem — it has no backing disk storage;
    its files are generated by the kernel on-read and written directly to
    kernel memory structures on-write
  • The difference between reading kernel state (/proc status files) and
    changing it (/proc/sys tunables)
  • That sysctl parameter names map directly to paths under /proc/sys/,
    with dots replacing slashes (e.g., net.ipv4.ip_forward = /proc/sys/net/ipv4/ip_forward)

Commands You'll Use:
  • cat / echo      - Read and write /proc files directly
  • sysctl -a       - List all tunable kernel parameters and current values
  • sysctl -w       - Write a tunable value (runtime, not persistent)
  • sysctl -p       - Apply settings from a sysctl.d config file
  • sysctl --system - Apply all settings from all sysctl.d config files

Files You'll Interact With:
  • /proc/                     - Kernel interface pseudo-filesystem
  • /proc/sys/                 - Tunable kernel parameters
  • /proc/meminfo              - Memory segment details
  • /proc/cpuinfo              - CPU details
  • /etc/sysctl.d/             - Drop-in directory for persistent sysctl settings
  • /usr/lib/sysctl.d/         - Package-provided sysctl defaults (do not edit)

KEY CONCEPT — /proc/sys and sysctl name mapping:
  /proc/sys/net/ipv4/ip_forward   ←→   net.ipv4.ip_forward
  /proc/sys/vm/swappiness         ←→   vm.swappiness
  /proc/sys/kernel/hostname       ←→   kernel.hostname

  The path separator '/' becomes '.' in sysctl notation.
  Both representations refer to the same kernel value.
EOF
}

#############################################################################
# SCENARIO
#############################################################################
scenario() {
    cat << 'EOF'
SCENARIO:
You are configuring a RHEL server that will act as a router between two
network segments. IP forwarding is currently disabled (the kernel default
for servers). You need to enable it at runtime for immediate effect, then
make the change persistent so it survives reboots. You will also explore
the /proc filesystem to understand what kernel state information is available.

BACKGROUND:
Changes written directly to /proc/sys/ are immediate but lost on reboot.
Persistent changes require a file in /etc/sysctl.d/. The sysctl utility
bridges both approaches — it can write runtime values and read/apply
persistent config files.

OBJECTIVES:
  1. Explore /proc by reading /proc/meminfo, /proc/cpuinfo (first 20 lines),
     and /proc/version. Note what information is available and how it is
     structured. Then use sysctl -a to see all tunable parameters.

  2. Read the current value of net.ipv4.ip_forward using both methods:
     • Direct file read: cat /proc/sys/net/ipv4/ip_forward
     • sysctl: sysctl net.ipv4.ip_forward
     Both should show 0. Then enable it at runtime using sysctl -w.

  3. Make net.ipv4.ip_forward=1 persistent by creating
     /etc/sysctl.d/lab21b.conf with the appropriate content.
     Apply the file immediately using sysctl -p /etc/sysctl.d/lab21b.conf
     and verify the value is still 1.

HINTS:
  • sysctl -w net.ipv4.ip_forward=1 — writes directly, no file needed
  • sysctl -p <file> — loads and applies a specific sysctl config file
  • The format in sysctl.d files is: parameter = value (spaces around = are fine)
  • sysctl -a | grep forward — useful for finding the right parameter name

SUCCESS CRITERIA:
  • net.ipv4.ip_forward is currently set to 1 (runtime)
  • /etc/sysctl.d/lab21b.conf exists and contains net.ipv4.ip_forward = 1
EOF
}

#############################################################################
# QUICK OBJECTIVES
#############################################################################
objectives_quick() {
    cat << 'EOF'
  ☐ 1. Explore /proc/meminfo, /proc/cpuinfo, /proc/version and sysctl -a
  ☐ 2. Read net.ipv4.ip_forward via both /proc and sysctl; enable it at runtime
  ☐ 3. Create /etc/sysctl.d/lab21b.conf with net.ipv4.ip_forward = 1; apply with sysctl -p
EOF
}

#############################################################################
# INTERACTIVE MODE
#############################################################################
get_step_count() {
    echo "3"
}

scenario_context() {
    cat << 'EOF'
A RHEL server needs to be configured as a router. IP forwarding is disabled
by default. You will explore the /proc filesystem, enable ip_forward at
runtime, and then make it persistent using sysctl.
EOF
}

# STEP 1
show_step_1() {
    cat << 'EOF'
TASK: Explore the /proc pseudo-filesystem

Read several key /proc status files and use sysctl -a to see all tunables.
The goal is to understand the range of kernel information exposed through /proc.

Requirements:
  • Read /proc/meminfo — note that these values are live kernel memory stats
  • Read the first 20 lines of /proc/cpuinfo — note the processor details
  • Read /proc/version — shows kernel version and build info
  • Run sysctl -a and observe the parameter naming convention

Commands you might need:
  • cat /proc/meminfo
  • head -20 /proc/cpuinfo
  • cat /proc/version
  • sysctl -a
  • sysctl -a | wc -l    (count total tunables)
  • sysctl -a | grep net.ipv4
EOF
}

validate_step_1() {
    # Observational — verify /proc is accessible
    if cat /proc/version >/dev/null 2>&1; then
        return 0
    fi
    echo ""
    print_color "$RED" "✗ Cannot read /proc/version — /proc may not be mounted"
    return 1
}

solution_step_1() {
    cat << 'EOF'

SOLUTION:
─────────
Commands:
  cat /proc/meminfo
  head -20 /proc/cpuinfo
  cat /proc/version
  sysctl -a
  sysctl -a | wc -l

Key observations:
  • /proc/meminfo: MemTotal, MemFree, Cached, SwapTotal, etc. — these are the
    same values tools like 'free' and 'top' read from.
  • /proc/cpuinfo: one block per logical CPU. Fields like 'model name',
    'cpu MHz', 'flags' (supported instruction sets), and 'cpu cores'.
  • /proc/version: kernel version string, gcc version used to compile it,
    and the build timestamp.
  • sysctl -a: hundreds of parameters across namespaces: kernel.*, net.*, vm.*,
    fs.*, dev.*. These are all the knobs available without recompiling the kernel.

Why this matters:
  Many performance and monitoring tools (vmstat, free, ss, netstat) are simply
  formatted readers of /proc files. Understanding /proc lets you go directly
  to the source when a tool isn't available.

EOF
}

hint_step_2() {
    echo "  Read with: cat /proc/sys/net/ipv4/ip_forward"
    echo "  Enable with: sysctl -w net.ipv4.ip_forward=1"
}

# STEP 2
show_step_2() {
    cat << 'EOF'
TASK: Read and enable IP forwarding at runtime

Demonstrate that /proc/sys and sysctl are two views of the same kernel value,
then enable net.ipv4.ip_forward using sysctl -w.

Requirements:
  • Read the current value via direct /proc path (should be 0)
  • Read the same value via sysctl notation (should also be 0)
  • Enable IP forwarding at runtime using sysctl -w
  • Verify the change via both methods again (both should show 1)

Commands you might need:
  • cat /proc/sys/net/ipv4/ip_forward
  • sysctl net.ipv4.ip_forward
  • sysctl -w net.ipv4.ip_forward=1
  • cat /proc/sys/net/ipv4/ip_forward   (verify after change)
EOF
}

validate_step_2() {
    local current_val
    current_val=$(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null)

    if [ "$current_val" = "1" ]; then
        return 0
    fi

    echo ""
    print_color "$RED" "✗ net.ipv4.ip_forward is '$current_val' (expected 1)"
    echo "  Fix: sysctl -w net.ipv4.ip_forward=1"
    return 1
}

solution_step_2() {
    cat << 'EOF'

SOLUTION:
─────────
Commands:
  # Read current value — both show the same kernel data
  cat /proc/sys/net/ipv4/ip_forward
  sysctl net.ipv4.ip_forward

  # Enable at runtime
  sysctl -w net.ipv4.ip_forward=1

  # Verify
  cat /proc/sys/net/ipv4/ip_forward
  sysctl net.ipv4.ip_forward

Explanation:
  • cat /proc/sys/net/ipv4/ip_forward: reads the file directly. /proc/sys
    files are not real files — reading them causes the kernel to report the
    current value of an in-memory variable.
  • echo 1 > /proc/sys/net/ipv4/ip_forward: also works as an alternative to
    sysctl -w. Writing to /proc/sys files directly updates the kernel variable
    immediately. sysctl -w is just a more readable wrapper around this.
  • sysctl -w: writes the value AND prints confirmation:
    net.ipv4.ip_forward = 1

IMPORTANT — this change is NOT persistent:
  /proc/sys is reset to kernel defaults on every reboot. Writing here
  is identical to writing to a running process's memory — it's gone when
  the system restarts. Persistence requires /etc/sysctl.d/ (next step).

Verification:
  cat /proc/sys/net/ipv4/ip_forward
  # Expected: 1

EOF
}

hint_step_3() {
    echo "  Create /etc/sysctl.d/lab21b.conf with: net.ipv4.ip_forward = 1"
    echo "  Then apply with: sysctl -p /etc/sysctl.d/lab21b.conf"
}

# STEP 3
show_step_3() {
    cat << 'EOF'
TASK: Make the IP forwarding change persistent with sysctl.d

Create a drop-in configuration file in /etc/sysctl.d/ so the change
survives reboot. Then apply it immediately using sysctl -p to confirm
the file is correctly formed.

Requirements:
  • Create /etc/sysctl.d/lab21b.conf
  • The file must contain: net.ipv4.ip_forward = 1
  • Apply the file with sysctl -p and verify net.ipv4.ip_forward is still 1

Commands you might need:
  • echo 'net.ipv4.ip_forward = 1' > /etc/sysctl.d/lab21b.conf
  • sysctl -p /etc/sysctl.d/lab21b.conf
  • sysctl net.ipv4.ip_forward
EOF
}

validate_step_3() {
    if [ ! -f /etc/sysctl.d/lab21b.conf ]; then
        echo ""
        print_color "$RED" "✗ /etc/sysctl.d/lab21b.conf does not exist"
        echo "  Fix: echo 'net.ipv4.ip_forward = 1' > /etc/sysctl.d/lab21b.conf"
        return 1
    fi

    if ! grep -q "net.ipv4.ip_forward" /etc/sysctl.d/lab21b.conf; then
        echo ""
        print_color "$RED" "✗ /etc/sysctl.d/lab21b.conf does not contain net.ipv4.ip_forward"
        echo "  Fix: echo 'net.ipv4.ip_forward = 1' > /etc/sysctl.d/lab21b.conf"
        return 1
    fi

    if ! grep -qE "net\.ipv4\.ip_forward\s*=\s*1" /etc/sysctl.d/lab21b.conf; then
        echo ""
        print_color "$RED" "✗ net.ipv4.ip_forward is not set to 1 in /etc/sysctl.d/lab21b.conf"
        echo "  Contents: $(cat /etc/sysctl.d/lab21b.conf)"
        echo "  Fix: echo 'net.ipv4.ip_forward = 1' > /etc/sysctl.d/lab21b.conf"
        return 1
    fi

    return 0
}

solution_step_3() {
    cat << 'EOF'

SOLUTION:
─────────
Commands:
  echo 'net.ipv4.ip_forward = 1' > /etc/sysctl.d/lab21b.conf
  sysctl -p /etc/sysctl.d/lab21b.conf
  sysctl net.ipv4.ip_forward

Explanation:
  • /etc/sysctl.d/<name>.conf: drop-in directory for persistent sysctl settings.
    Files here are read and applied at boot by systemd-sysctl.service.
    The counterpart /usr/lib/sysctl.d/ holds package-provided defaults — do not
    edit those files; put overrides in /etc/sysctl.d/ instead.
  • File format: one setting per line as 'parameter = value'. Comments use #.
  • sysctl -p <file>: reads and immediately applies the specified file.
    Without a filename, -p reads /etc/sysctl.conf (legacy location).
  • sysctl --system: applies ALL sysctl.d files in order (useful for confirming
    the full set of settings that will be applied at boot).

Load order when multiple files exist:
  Files are applied alphabetically by filename. A file named 99-custom.conf
  will override settings from 10-default.conf for the same parameter.
  /etc/sysctl.d/ takes priority over /usr/lib/sysctl.d/ for the same filename.

Verification:
  cat /etc/sysctl.d/lab21b.conf
  # Expected: net.ipv4.ip_forward = 1

  sysctl net.ipv4.ip_forward
  # Expected: net.ipv4.ip_forward = 1

EOF
}

#############################################################################
# VALIDATION (Standard Mode)
#############################################################################
validate() {
    local score=0
    local total=2

    echo "Checking your configuration..."
    echo ""

    print_color "$CYAN" "[1/$total] Checking net.ipv4.ip_forward runtime value..."
    local current_val
    current_val=$(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null)
    if [ "$current_val" = "1" ]; then
        print_color "$GREEN" "  ✓ net.ipv4.ip_forward is 1 (enabled)"
        ((score++))
    else
        print_color "$RED" "  ✗ net.ipv4.ip_forward is '$current_val' (expected 1)"
        print_color "$YELLOW" "  Fix: sysctl -w net.ipv4.ip_forward=1"
    fi
    echo ""

    print_color "$CYAN" "[2/$total] Checking /etc/sysctl.d/lab21b.conf for persistent config..."
    if grep -qE "net\.ipv4\.ip_forward\s*=\s*1" /etc/sysctl.d/lab21b.conf 2>/dev/null; then
        print_color "$GREEN" "  ✓ Persistent config correctly set in /etc/sysctl.d/lab21b.conf"
        ((score++))
    else
        print_color "$RED" "  ✗ /etc/sysctl.d/lab21b.conf missing or value not set to 1"
        print_color "$YELLOW" "  Fix: echo 'net.ipv4.ip_forward = 1' > /etc/sysctl.d/lab21b.conf"
    fi
    echo ""

    print_color "$CYAN" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    print_color "$BOLD" "FINAL SCORE: $score/$total"

    if [ $score -eq $total ]; then
        print_color "$GREEN" "STATUS: ✓ PASSED"
        echo ""
        echo "Excellent! You can read /proc, modify kernel tunables at runtime, and make them persistent."
    else
        print_color "$YELLOW" "STATUS: ⚠ INCOMPLETE ($score/$total checks passed)"
        echo ""
        echo "Review the feedback above and try again."
        echo "Run with --solution to see detailed steps."
    fi
    print_color "$CYAN" "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

    export VALIDATION_SCORE=$score
    export VALIDATION_TOTAL=$total
    [ $score -eq $total ]
}

#############################################################################
# SOLUTION (Standard Mode)
#############################################################################
solution() {
    cat << 'EOF'
COMPLETE SOLUTION WALKTHROUGH
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 1: Explore /proc
─────────────────────────────────────────────────────────────────
  cat /proc/meminfo
  head -20 /proc/cpuinfo
  cat /proc/version
  sysctl -a | wc -l


STEP 2: Read and enable IP forwarding at runtime
─────────────────────────────────────────────────────────────────
  cat /proc/sys/net/ipv4/ip_forward   # shows 0
  sysctl net.ipv4.ip_forward          # same value, different notation
  sysctl -w net.ipv4.ip_forward=1
  cat /proc/sys/net/ipv4/ip_forward   # now shows 1


STEP 3: Make the change persistent
─────────────────────────────────────────────────────────────────
  echo 'net.ipv4.ip_forward = 1' > /etc/sysctl.d/lab21b.conf
  sysctl -p /etc/sysctl.d/lab21b.conf
  sysctl net.ipv4.ip_forward


CONCEPTUAL UNDERSTANDING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/proc is Not a Real Filesystem:
  Files in /proc have no inode on disk. Reading them triggers the kernel to
  generate output from in-memory data structures. Writing to /proc/sys files
  modifies kernel variables in memory directly — instantly, without a syscall
  to a daemon or service. This is as close to "talking to the kernel" as you
  can get from userspace without writing a kernel module.

sysctl.d Load Priority:
  /usr/lib/sysctl.d/   → package defaults (lowest priority)
  /run/sysctl.d/       → runtime overrides (ephemeral)
  /etc/sysctl.d/       → admin overrides (highest priority)
  /etc/sysctl.conf     → legacy single-file location (still works)

  Within each directory, files load alphabetically. Name your files with a
  numeric prefix (e.g., 90-router.conf) to control precedence explicitly.

Why net.ipv4.ip_forward Matters:
  By default, Linux drops packets not addressed to itself — it behaves as a
  host, not a router. Setting ip_forward=1 tells the kernel to forward packets
  between interfaces, which is required for NAT, routing, and container
  networking (Docker and Podman depend on this).


COMMON MISTAKES & TROUBLESHOOTING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Mistake 1: Writing to /proc/sys but forgetting the sysctl.d file
  Result: Change works until next reboot, then disappears
  Fix: Always pair runtime changes with a sysctl.d config file

Mistake 2: Editing /usr/lib/sysctl.d/ files directly
  Result: Changes get overwritten on next package update
  Fix: Always put overrides in /etc/sysctl.d/

Mistake 3: Using sysctl -p with no filename after adding a new file
  Result: Only reads /etc/sysctl.conf (legacy), misses your new file
  Fix: sysctl -p /etc/sysctl.d/yourfile.conf, or sysctl --system for all files


EXAM TIPS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Runtime change: sysctl -w parameter=value  (or echo value > /proc/sys/path)
2. Persistent change: /etc/sysctl.d/<name>.conf, then sysctl -p <file>
3. Verify with: sysctl <parameter> or cat /proc/sys/<path>
4. The dot-to-slash mapping (net.ipv4.ip_forward ↔ /proc/sys/net/ipv4/ip_forward)
   is tested — know it both ways

EOF
}

#############################################################################
# CLEANUP
#############################################################################
cleanup_lab() {
    echo "Cleaning up lab environment..."

    rm -f /etc/sysctl.d/lab21b.conf 2>/dev/null || true
    echo 0 > /proc/sys/net/ipv4/ip_forward 2>/dev/null || true

    echo "  ✓ Removed /etc/sysctl.d/lab21b.conf"
    echo "  ✓ Reset net.ipv4.ip_forward to 0"
}

main "$@"
